name: wd-commonjs-webdriver-manager-mocha-chai

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: INSTALL
        run: |
          npm ci
        env:
          CI: true
      - name: UPDATE & START WEBDRIVER
        run: |
          npm run upadte-webderiver
          npm run start-webderiver
      - name: TEST
        run: |
          npm run test
        env:
          BROWSER: chrome
